version: '3.7'

services:
  restream:
    environment:
      TZ: ${TZ}
    container_name: restream
    restart: always
    image: mamau/restream:latest
    ports:
      - 8089:8089
    volumes:
      - ./:/storage

  redis:
    image: redis:alpine
    container_name: redis-restream
    ports:
      - ${REDIS_PORT}:6379

  nginx_rtmp:
    container_name: nginx-rtmp
    image: alfg/nginx-rtmp:latest
    ports:
      - 1935:1935
      - 8080:80
